<?php
	include_once("./DB_connect.php");
	include_once("./Class/class_user.php");
		
	$request = "SELECT DISTINCT utilisateurs.id AS user_id, utilisateurs.prenom AS user_prenom, utilisateurs.nom AS user_nom FROM utilisateurs JOIN tickets ON utilisateurs.id = tickets.utilisateur_id JOIN ticket_entry ON tickets.id = ticket_entry.ticket_id JOIN produits ON ticket_entry.produit_id = produits.id WHERE produits.id = :TheProductId";
	
	$Users_bdd = $pdo->prepare($request);
	$Users_bdd->bindParam(':TheProductId', $TheProductId);
	$Users_bdd->setFetchMode(PDO::FETCH_CLASS, 'user');
	
	$TheProductId = $_GET['ProductId'];
	$Users_bdd->execute();
	$Users = array();
	$i = 0;
	foreach ($Users_bdd->fetchAll() as $user) {
		$Users[$i] = $user;
		$i = $i+1;
	}
?>

	<table border="1" class="w3-table">
		<tr>
			<th>ID</th>
			<th>Prénom</th>
			<th>Nom</th>
			<th>Lien</th>
		<!-- </tr> generated by php for code alignement in safari inspector -->
		<?php
			echo "</tr>\n";  // here and not above just for visual code alignement in safari inspector (there was a bug)
			foreach($Users as $user){
				echo $user;
			}
		?>
	</table>